# Generated by Django 5.2 on 2025-07-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_receiver_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
