# Generated by ChatGPT on 2024-06-10
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_customerservicemessage_customerservicereply"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("recipient_type", models.CharField(max_length=10, choices=[("student", "Student"), ("mentor", "Mentor")])),
                ("recipient_id", models.PositiveIntegerField()),
                ("recipient_content_type", models.ForeignKey(to="contenttypes.ContentType", on_delete=django.db.models.deletion.CASCADE)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_email_sent", models.BooleanField(default=False)),
            ],
        ),
    ] 