# Generated by Django 5.0.1 on 2025-07-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
