# Generated by Django 5.2 on 2025-04-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='expertise',
        ),
    ]
