# Generated by Django 5.2 on 2025-04-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_remove_mentor_expertise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={},
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='mentor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
