# Generated by Django 5.2 on 2025-04-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mentor', '0004_alter_mentor_options_mentor_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups this mentor belongs to.', related_name='mentor_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='User-specific permissions for this mentor.', related_name='mentor_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
