# Generated by Django 5.2 on 2025-04-22 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0005_alter_mentor_groups_alter_mentor_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='mentor.mentor', verbose_name='Mentor')),
            ],
            options={
                'verbose_name': 'Mentor Token',
                'verbose_name_plural': 'Mentor Tokens',
            },
        ),
    ]
