# Generated by Django 5.2 on 2025-04-23 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0006_mentortoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MentorDetail',
            fields=[
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to='mentor.mentor')),
                ('first_name', models.CharField(default='John', max_length=100)),
                ('last_name', models.CharField(default='Doe', max_length=100)),
                ('dob', models.DateField(default='2000-01-01')),
                ('age', models.PositiveIntegerField(default=25)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(default='0000000000', max_length=15, unique=True)),
                ('college', models.CharField(default='Unknown College', max_length=200)),
                ('cgpa', models.FloatField(default=0.0)),
                ('batch', models.PositiveIntegerField(default=2024)),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('about', models.TextField(default='No information provided.')),
                ('availability_timings', models.CharField(default='9 AM - 5 PM', max_length=50)),
                ('profile_photo', models.ImageField(blank=True, default=None, null=True, upload_to='profile_photos/')),
                ('cv', models.FileField(blank=True, default=None, null=True, upload_to='cvs/')),
                ('is_approved', models.BooleanField(default=False)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('professions', models.ManyToManyField(blank=True, related_name='mentors', to='mentor.profession')),
                ('skills', models.ManyToManyField(blank=True, related_name='mentors', to='mentor.skill')),
            ],
        ),
    ]
