# Generated by Django 5.2 on 2025-04-23 19:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0007_profession_skill_mentordetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Earning amount in USD', max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date when the earning was received')),
                ('source', models.CharField(help_text='Source of the earning (e.g., Session with Student X)', max_length=100)),
                ('transaction_id', models.CharField(blank=True, help_text='Payment gateway transaction ID if available', max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this earning', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='mentor.mentor')),
            ],
            options={
                'verbose_name': 'Mentor Earning',
                'verbose_name_plural': 'Mentor Earnings',
                'ordering': ['-date'],
            },
        ),
    ]
