# Generated by Django 5.2 on 2025-04-23 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0009_mentormessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(editable=False, max_length=16, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(default=60, help_text='Duration in minutes')),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], default='scheduled', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='mentor.mentor')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor Meeting',
                'verbose_name_plural': 'Mentor Meetings',
                'ordering': ['-scheduled_time'],
                'indexes': [models.Index(fields=['meeting_id'], name='mentor_meet_meeting_7e742f_idx'), models.Index(fields=['mentor'], name='mentor_meet_mentor__da9e85_idx'), models.Index(fields=['status'], name='mentor_meet_status_a0cdc4_idx'), models.Index(fields=['scheduled_time'], name='mentor_meet_schedul_4c7802_idx')],
            },
        ),
    ]
