# Generated by Django 5.2 on 2025-04-26 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0011_alter_mentordetail_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentordetail',
            name='mentor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to='mentor.mentor'),
        ),
    ]
