# Generated by Django 5.2 on 2025-04-29 19:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0012_alter_mentordetail_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentormessage',
            name='message_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
