# Generated by Django 5.2 on 2025-04-29 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0013_mentormessage_message_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('QUOTE', 'Quote')], max_length=5)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='mentor_posts/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='mentor_posts/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='mentor.mentor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
