# Generated by Django 5.2 on 2025-06-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0015_alter_mentordetail_age_alter_mentordetail_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentordetail',
            name='total_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
