# Generated by Django 5.2 on 2025-06-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0016_mentordetail_total_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentordetail',
            name='about',
            field=models.TextField(default='#NA'),
        ),
        migrations.AlterField(
            model_name='mentordetail',
            name='availability_timings',
            field=models.CharField(default='#NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='mentordetail',
            name='college',
            field=models.CharField(default='#NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='mentordetail',
            name='phone_number',
            field=models.CharField(default='#NA', max_length=15),
        ),
        migrations.AlterField(
            model_name='mentordetail',
            name='profile_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='mentors/profile_photos/'),
        ),
    ]
