# Generated by Django 5.2 on 2025-06-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0017_alter_mentordetail_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentordetail',
            name='cv',
            field=models.FileField(blank=True, default=None, null=True, upload_to='mentors/cvs/'),
        ),
    ]
