# Generated by Django 5.2 on 2025-06-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0019_meeting_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='transaction_id',
        ),
    ]
