# Generated by Django 5.2 on 2025-07-12 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0021_mentornote'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_attended', models.BooleanField(default=False)),
                ('student_attended', models.BooleanField(default=False)),
                ('mentor_join_time', models.DateTimeField(blank=True, null=True)),
                ('student_join_time', models.DateTimeField(blank=True, null=True)),
                ('mentor_leave_time', models.DateTimeField(blank=True, null=True)),
                ('student_leave_time', models.DateTimeField(blank=True, null=True)),
                ('mentor_duration', models.PositiveIntegerField(default=0, help_text='Duration mentor was in meeting (minutes)')),
                ('student_duration', models.PositiveIntegerField(default=0, help_text='Duration student was in meeting (minutes)')),
                ('notes', models.TextField(blank=True, help_text='Any notes about the attendance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='mentor.meeting')),
            ],
            options={
                'verbose_name': 'Meeting Attendance',
                'verbose_name_plural': 'Meeting Attendances',
                'ordering': ['-created_at'],
            },
        ),
    ]
