# Generated by Django 5.2 on 2025-07-12 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0022_meetingattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Withdrawal amount in USD', max_digits=10)),
                ('request_date', models.DateTimeField(auto_now_add=True, help_text='Date when the withdrawal was requested')),
                ('processed_date', models.DateTimeField(blank=True, help_text='Date when the withdrawal was processed', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('payment_method', models.CharField(default='bank_transfer', help_text='Payment method for withdrawal', max_length=50)),
                ('bank_details', models.TextField(blank=True, help_text='Bank account details for transfer', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this withdrawal', null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Payment gateway transaction ID if available', max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='mentor.mentor')),
            ],
            options={
                'verbose_name': 'Mentor Withdrawal',
                'verbose_name_plural': 'Mentor Withdrawals',
                'ordering': ['-request_date'],
            },
        ),
    ]
