# Generated by Django 5.2 on 2025-07-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0023_withdrawal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingAttendance',
        ),
    ]
