# Generated by Django 5.2 on 2025-07-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0024_delete_meetingattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentordetail',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mentordetail',
            name='availability_timings',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mentordetail',
            name='college',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mentordetail',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mentordetail',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mentordetail',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='mentordetail',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mentordetail',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
