# Generated by Django 5.0.1 on 2025-07-18 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0025_alter_mentordetail_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentordetail',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('mentor', 'Mentor'), ('student', 'Student')], max_length=10)),
                ('attended_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='mentor.meeting')),
            ],
            options={
                'ordering': ['attended_at'],
                'unique_together': {('meeting', 'user_id', 'role')},
            },
        ),
    ]
