# Generated by Django 5.0.1 on 2025-07-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0026_alter_mentordetail_dob_meetingattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='earning',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Earning amount in INR (₹)', max_digits=10),
        ),
    ]
