# Generated by Django 5.0.1 on 2025-07-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0027_mentor_accepted_terms_alter_earning_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='mentor_attendance_key',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='mentor_attendance_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='mentor_attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='student_attendance_key',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='student_attendance_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='student_attended',
            field=models.BooleanField(default=False),
        ),
    ]
