# Generated by Django 5.2 on 2025-07-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0028_meeting_mentor_attendance_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentordetail',
            name='cv',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mentordetail',
            name='profile_photo',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
