# Generated by Django 5.2 on 2025-07-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0029_alter_mentordetail_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentordetail',
            name='cv',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
