# Generated by Django 5.2 on 2025-08-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0030_alter_mentordetail_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentordetail',
            name='github_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mentordetail',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mentordetail',
            name='portfolio_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
