# Generated by Django 5.2 on 2025-08-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0032_add_mentor_detail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentor',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
