# Generated by Django 5.2 on 2025-08-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0033_mentor_is_online_mentor_last_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='mentordetail',
            name='batch',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='mentordetail',
            name='college',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='mentordetail',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mentordetail',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mentormessage',
            name='subject',
            field=models.CharField(max_length=400),
        ),
    ]
