# Generated by Django 5.2 on 2025-04-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups this student belongs to.', related_name='student_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='User-specific permissions for this student.', related_name='student_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
