# Generated by Django 5.2.3 on 2025-06-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_successstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
