# Generated by Django 5.2 on 2025-06-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_profession_skill_studentdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='availability_timings',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='total_students',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='years_of_experience',
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='cv',
            field=models.FileField(blank=True, default=None, null=True, upload_to='student/cvs/'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='professions',
            field=models.ManyToManyField(blank=True, related_name='students', to='student.profession'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='profile_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='student/profile_photos/'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='students', to='student.skill'),
        ),
    ]
