# Generated by Django 5.2 on 2025-06-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_studentdetail_availability_timings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='cgpa',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='college',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
