# Generated by Django 5.2 on 2025-06-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_studentdetail_about_alter_studentdetail_cgpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='cv',
            field=models.FileField(blank=True, default=None, max_length=255, null=True, upload_to='student/cvs/'),
        ),
    ]
