# Generated by Django 5.2 on 2025-06-28 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_studentmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmessage',
            name='admin_sender',
        ),
        migrations.AddField(
            model_name='studentmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_student_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentmessage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
