# Generated by Django 5.2 on 2025-07-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0024_delete_meetingattendance'),
        ('student', '0011_feedback'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('student', 'meeting')},
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('student', 'meeting'), name='unique_student_meeting_feedback'),
        ),
    ]
