# Generated by Django 5.0.1 on 2025-07-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_feedback_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
