# Generated by Django 5.0.1 on 2025-07-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_student_accepted_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='batch',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='cgpa',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='is_approved',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='total_sessions',
            field=models.PositiveIntegerField(),
        ),
    ]
