# Generated by Django 5.2 on 2025-07-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_studentdetail_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='cv',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
