# Generated by Django 5.2 on 2025-08-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_alter_studentdetail_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='college',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='profile_photo',
            field=models.URLField(blank=True, default=None, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='studentmessage',
            name='subject',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='title',
            field=models.CharField(max_length=555),
        ),
    ]
