# Generated by Django 5.2 on 2025-08-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_add_booking_day_date_fields'),
        ('student', '0018_alter_studentdetail_college_and_more'),
    ]

    operations = [
    ]
