# Generated by Django 5.2 on 2025-08-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_merge_20250804_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_duration',
            field=models.CharField(default='60 min', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=10),
        ),
    ]
