# Generated by Django 5.2 on 2025-08-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_admin_post',
            field=models.BooleanField(default=False, help_text='Mark this post as an official AspireX admin post.'),
        ),
    ]
